[workspace]

members = [
  "dayx",
]

[workspace.package]
version = "0.1.0"
authors = ["Andreas Andersson <andreas@neoboid.com"]
edition = "2021"
homepage = "https://www.neoboid.com"
repository = "https://www.github.com/derwiath/adventofcode-2022"
