[package]
name = "day3"
description = "Solving day3 for advent of code 2022"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
regex.workspace = true
lazy_static.workspace = true
